"""
test_e2e_countries.py — E2E country coverage battery.

Tests every city/country pair in the catalog through the full 11-specialist
orchestrator.negotiate() path. Asserts: no crash, known outcome, var-0 stability.

Warzone countries excluded per EXC-WAR-2 (active conflicts 2026).
Run: cd society && python3 -m pytest test_e2e_countries.py -q
"""
import json
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from tests.test_composition_wiring import build_society  # reuse the full-society harness

# Warzone exclusions — EXC-WAR-2 aligned (active conflicts 2026)
WARZONE_ISO = frozenset({
    "RU", "UA", "SY", "YE", "AF", "MM", "SD", "SS", "SO", "LY",
    "ML", "NE", "CF", "HT", "KP", "BF", "IQ", "PS", "ER", "CD",
})

_KNOWN_OUTCOMES = {"success", "cannot_satisfy", "needs_consent", "proposed"}


def _trip(city, country_iso, nationality="US", budget=400000,
          checkin="2026-10-01", checkout="2026-10-05", vibe="culture",
          today="2026-06-18"):
    return {
        "user_id": "e2e-test",
        "total_budget_cents": budget,
        "nationality": nationality,
        "today": today,
        "legs": [{"city": city, "dest_country": country_iso,
                  "checkin": checkin, "checkout": checkout,
                  "adults": 2, "vibe": vibe}],
    }


# CASES: (label, city, country_iso, nationality, vibe)
# Sourced from catalog.json — every non-warzone city/country pair.
# Top-20 destinations carry SG/AU/IN nationality variants for discrimination coverage.
CASES = [
    ('bali_US', 'bali', 'ID', 'US', 'beach'),
    ('bali_SG', 'bali', 'ID', 'SG', 'beach'),
    ('bali_AU', 'bali', 'ID', 'AU', 'beach'),
    ('bali_IN', 'bali', 'ID', 'IN', 'beach'),
    ('bangkok_US', 'bangkok', 'TH', 'US', 'culture'),
    ('bangkok_SG', 'bangkok', 'TH', 'SG', 'culture'),
    ('bangkok_AU', 'bangkok', 'TH', 'AU', 'culture'),
    ('bangkok_IN', 'bangkok', 'TH', 'IN', 'culture'),
    ('singapore_US', 'singapore', 'SG', 'US', 'culture'),
    ('singapore_SG', 'singapore', 'SG', 'SG', 'culture'),
    ('singapore_AU', 'singapore', 'SG', 'AU', 'culture'),
    ('singapore_IN', 'singapore', 'SG', 'IN', 'culture'),
    ('kuala_lumpur_US', 'kuala lumpur', 'MY', 'US', 'culture'),
    ('port_moresby_US', 'port moresby', 'PG', 'US', 'culture'),
    ('perth_US', 'perth', 'AU', 'US', 'culture'),
    ('perth_SG', 'perth', 'AU', 'SG', 'culture'),
    ('perth_AU', 'perth', 'AU', 'AU', 'culture'),
    ('perth_IN', 'perth', 'AU', 'IN', 'culture'),
    ('busselton_US', 'busselton', 'AU', 'US', 'culture'),
    ('busselton_SG', 'busselton', 'AU', 'SG', 'culture'),
    ('busselton_AU', 'busselton', 'AU', 'AU', 'culture'),
    ('busselton_IN', 'busselton', 'AU', 'IN', 'culture'),
    ('margaret_river_US', 'margaret-river', 'AU', 'US', 'culture'),
    ('margaret_river_SG', 'margaret-river', 'AU', 'SG', 'culture'),
    ('margaret_river_AU', 'margaret-river', 'AU', 'AU', 'culture'),
    ('margaret_river_IN', 'margaret-river', 'AU', 'IN', 'culture'),
    ('pemberton_US', 'pemberton', 'AU', 'US', 'culture'),
    ('pemberton_SG', 'pemberton', 'AU', 'SG', 'culture'),
    ('pemberton_AU', 'pemberton', 'AU', 'AU', 'culture'),
    ('pemberton_IN', 'pemberton', 'AU', 'IN', 'culture'),
    ('albany_US', 'albany', 'AU', 'US', 'culture'),
    ('albany_SG', 'albany', 'AU', 'SG', 'culture'),
    ('albany_AU', 'albany', 'AU', 'AU', 'culture'),
    ('albany_IN', 'albany', 'AU', 'IN', 'culture'),
    ('ravensthorpe_US', 'ravensthorpe', 'AU', 'US', 'culture'),
    ('ravensthorpe_SG', 'ravensthorpe', 'AU', 'SG', 'culture'),
    ('ravensthorpe_AU', 'ravensthorpe', 'AU', 'AU', 'culture'),
    ('ravensthorpe_IN', 'ravensthorpe', 'AU', 'IN', 'culture'),
    ('esperance_US', 'esperance', 'AU', 'US', 'culture'),
    ('esperance_SG', 'esperance', 'AU', 'SG', 'culture'),
    ('esperance_AU', 'esperance', 'AU', 'AU', 'culture'),
    ('esperance_IN', 'esperance', 'AU', 'IN', 'culture'),
    ('kalgoorlie_US', 'kalgoorlie', 'AU', 'US', 'culture'),
    ('kalgoorlie_SG', 'kalgoorlie', 'AU', 'SG', 'culture'),
    ('kalgoorlie_AU', 'kalgoorlie', 'AU', 'AU', 'culture'),
    ('kalgoorlie_IN', 'kalgoorlie', 'AU', 'IN', 'culture'),
    ('northam_US', 'northam', 'AU', 'US', 'culture'),
    ('northam_SG', 'northam', 'AU', 'SG', 'culture'),
    ('northam_AU', 'northam', 'AU', 'AU', 'culture'),
    ('northam_IN', 'northam', 'AU', 'IN', 'culture'),
    ('addis_ababa_US', 'addis ababa', 'ET', 'US', 'culture'),
    ('gondar_US', 'gondar', 'ET', 'US', 'culture'),
    ('lalibela_US', 'lalibela', 'ET', 'US', 'culture'),
    ('semera_US', 'semera', 'ET', 'US', 'culture'),
    ('phuket_US', 'phuket', 'TH', 'US', 'beach'),
    ('phuket_SG', 'phuket', 'TH', 'SG', 'beach'),
    ('phuket_AU', 'phuket', 'TH', 'AU', 'beach'),
    ('phuket_IN', 'phuket', 'TH', 'IN', 'beach'),
    ('krabi_US', 'krabi', 'TH', 'US', 'beach'),
    ('krabi_SG', 'krabi', 'TH', 'SG', 'beach'),
    ('krabi_AU', 'krabi', 'TH', 'AU', 'beach'),
    ('krabi_IN', 'krabi', 'TH', 'IN', 'beach'),
    ('ko_samui_US', 'ko samui', 'TH', 'US', 'beach'),
    ('ko_samui_SG', 'ko samui', 'TH', 'SG', 'beach'),
    ('ko_samui_AU', 'ko samui', 'TH', 'AU', 'beach'),
    ('ko_samui_IN', 'ko samui', 'TH', 'IN', 'beach'),
    ('istanbul_US', 'istanbul', 'TR', 'US', 'culture'),
    ('ankara_US', 'ankara', 'TR', 'US', 'culture'),
    ('goreme_US', 'goreme', 'TR', 'US', 'culture'),
    ('antalya_US', 'antalya', 'TR', 'US', 'beach'),
    ('tokyo_US', 'tokyo', 'JP', 'US', 'culture'),
    ('tokyo_SG', 'tokyo', 'JP', 'SG', 'culture'),
    ('tokyo_AU', 'tokyo', 'JP', 'AU', 'culture'),
    ('tokyo_IN', 'tokyo', 'JP', 'IN', 'culture'),
    ('osaka_US', 'osaka', 'JP', 'US', 'culture'),
    ('osaka_SG', 'osaka', 'JP', 'SG', 'culture'),
    ('osaka_AU', 'osaka', 'JP', 'AU', 'culture'),
    ('osaka_IN', 'osaka', 'JP', 'IN', 'culture'),
    ('kyoto_US', 'kyoto', 'JP', 'US', 'culture'),
    ('kyoto_SG', 'kyoto', 'JP', 'SG', 'culture'),
    ('kyoto_AU', 'kyoto', 'JP', 'AU', 'culture'),
    ('kyoto_IN', 'kyoto', 'JP', 'IN', 'culture'),
    ('hanoi_US', 'hanoi', 'VN', 'US', 'culture'),
    ('ho_chi_minh_US', 'ho chi minh', 'VN', 'US', 'culture'),
    ('da_nang_US', 'da nang', 'VN', 'US', 'culture'),
    ('nadi_US', 'nadi', 'FJ', 'US', 'beach'),
    ('suva_US', 'suva', 'FJ', 'US', 'culture'),
    ('apia_US', 'apia', 'WS', 'US', 'culture'),
    ('auckland_US', 'auckland', 'NZ', 'US', 'culture'),
    ('auckland_SG', 'auckland', 'NZ', 'SG', 'culture'),
    ('auckland_AU', 'auckland', 'NZ', 'AU', 'culture'),
    ('auckland_IN', 'auckland', 'NZ', 'IN', 'culture'),
    ('queenstown_US', 'queenstown', 'NZ', 'US', 'culture'),
    ('queenstown_SG', 'queenstown', 'NZ', 'SG', 'culture'),
    ('queenstown_AU', 'queenstown', 'NZ', 'AU', 'culture'),
    ('queenstown_IN', 'queenstown', 'NZ', 'IN', 'culture'),
    ('christchurch_US', 'christchurch', 'NZ', 'US', 'culture'),
    ('christchurch_SG', 'christchurch', 'NZ', 'SG', 'culture'),
    ('christchurch_AU', 'christchurch', 'NZ', 'AU', 'culture'),
    ('christchurch_IN', 'christchurch', 'NZ', 'IN', 'culture'),
    ('mexico_city_US', 'mexico city', 'MX', 'US', 'culture'),
    ('mexico_city_SG', 'mexico city', 'MX', 'SG', 'culture'),
    ('mexico_city_AU', 'mexico city', 'MX', 'AU', 'culture'),
    ('mexico_city_IN', 'mexico city', 'MX', 'IN', 'culture'),
    ('rio_de_janeiro_US', 'rio de janeiro', 'BR', 'US', 'culture'),
    ('rio_de_janeiro_SG', 'rio de janeiro', 'BR', 'SG', 'culture'),
    ('rio_de_janeiro_AU', 'rio de janeiro', 'BR', 'AU', 'culture'),
    ('rio_de_janeiro_IN', 'rio de janeiro', 'BR', 'IN', 'culture'),
    ('rome_US', 'rome', 'IT', 'US', 'culture'),
    ('rome_SG', 'rome', 'IT', 'SG', 'culture'),
    ('rome_AU', 'rome', 'IT', 'AU', 'culture'),
    ('rome_IN', 'rome', 'IT', 'IN', 'culture'),
    ('paris_US', 'paris', 'FR', 'US', 'culture'),
    ('paris_SG', 'paris', 'FR', 'SG', 'culture'),
    ('paris_AU', 'paris', 'FR', 'AU', 'culture'),
    ('paris_IN', 'paris', 'FR', 'IN', 'culture'),
    ('london_US', 'london', 'GB', 'US', 'culture'),
    ('london_SG', 'london', 'GB', 'SG', 'culture'),
    ('london_AU', 'london', 'GB', 'AU', 'culture'),
    ('london_IN', 'london', 'GB', 'IN', 'culture'),
    ('new_york_US', 'new york', 'US', 'US', 'culture'),
    ('new_york_SG', 'new york', 'US', 'SG', 'culture'),
    ('new_york_AU', 'new york', 'US', 'AU', 'culture'),
    ('new_york_IN', 'new york', 'US', 'IN', 'culture'),
    ('los_angeles_US', 'los angeles', 'US', 'US', 'culture'),
    ('los_angeles_SG', 'los angeles', 'US', 'SG', 'culture'),
    ('los_angeles_AU', 'los angeles', 'US', 'AU', 'culture'),
    ('los_angeles_IN', 'los angeles', 'US', 'IN', 'culture'),
    ('san_francisco_US', 'san francisco', 'US', 'US', 'culture'),
    ('san_francisco_SG', 'san francisco', 'US', 'SG', 'culture'),
    ('san_francisco_AU', 'san francisco', 'US', 'AU', 'culture'),
    ('san_francisco_IN', 'san francisco', 'US', 'IN', 'culture'),
    ('san_diego_US', 'san diego', 'US', 'US', 'culture'),
    ('san_diego_SG', 'san diego', 'US', 'SG', 'culture'),
    ('san_diego_AU', 'san diego', 'US', 'AU', 'culture'),
    ('san_diego_IN', 'san diego', 'US', 'IN', 'culture'),
    ('seattle_US', 'seattle', 'US', 'US', 'culture'),
    ('seattle_SG', 'seattle', 'US', 'SG', 'culture'),
    ('seattle_AU', 'seattle', 'US', 'AU', 'culture'),
    ('seattle_IN', 'seattle', 'US', 'IN', 'culture'),
    ('portland_US', 'portland', 'US', 'US', 'culture'),
    ('portland_SG', 'portland', 'US', 'SG', 'culture'),
    ('portland_AU', 'portland', 'US', 'AU', 'culture'),
    ('portland_IN', 'portland', 'US', 'IN', 'culture'),
    ('boston_US', 'boston', 'US', 'US', 'culture'),
    ('boston_SG', 'boston', 'US', 'SG', 'culture'),
    ('boston_AU', 'boston', 'US', 'AU', 'culture'),
    ('boston_IN', 'boston', 'US', 'IN', 'culture'),
    ('philadelphia_US', 'philadelphia', 'US', 'US', 'culture'),
    ('philadelphia_SG', 'philadelphia', 'US', 'SG', 'culture'),
    ('philadelphia_AU', 'philadelphia', 'US', 'AU', 'culture'),
    ('philadelphia_IN', 'philadelphia', 'US', 'IN', 'culture'),
    ('miami_US', 'miami', 'US', 'US', 'culture'),
    ('miami_SG', 'miami', 'US', 'SG', 'culture'),
    ('miami_AU', 'miami', 'US', 'AU', 'culture'),
    ('miami_IN', 'miami', 'US', 'IN', 'culture'),
    ('new_orleans_US', 'new orleans', 'US', 'US', 'culture'),
    ('new_orleans_SG', 'new orleans', 'US', 'SG', 'culture'),
    ('new_orleans_AU', 'new orleans', 'US', 'AU', 'culture'),
    ('new_orleans_IN', 'new orleans', 'US', 'IN', 'culture'),
    ('toronto_US', 'toronto', 'CA', 'US', 'culture'),
    ('montreal_US', 'montreal', 'CA', 'US', 'culture'),
    ('vancouver_US', 'vancouver', 'CA', 'US', 'culture'),
    ('frankfurt_US', 'frankfurt', 'DE', 'US', 'culture'),
    ('berlin_US', 'berlin', 'DE', 'US', 'culture'),
    ('amsterdam_US', 'amsterdam', 'NL', 'US', 'culture'),
    ('barcelona_US', 'barcelona', 'ES', 'US', 'culture'),
    ('barcelona_SG', 'barcelona', 'ES', 'SG', 'culture'),
    ('barcelona_AU', 'barcelona', 'ES', 'AU', 'culture'),
    ('barcelona_IN', 'barcelona', 'ES', 'IN', 'culture'),
    ('athens_US', 'athens', 'GR', 'US', 'culture'),
    ('athens_SG', 'athens', 'GR', 'SG', 'culture'),
    ('athens_AU', 'athens', 'GR', 'AU', 'culture'),
    ('athens_IN', 'athens', 'GR', 'IN', 'culture'),
    ('sao_paulo_US', 'sao paulo', 'BR', 'US', 'culture'),
    ('sao_paulo_SG', 'sao paulo', 'BR', 'SG', 'culture'),
    ('sao_paulo_AU', 'sao paulo', 'BR', 'AU', 'culture'),
    ('sao_paulo_IN', 'sao paulo', 'BR', 'IN', 'culture'),
    ('bogota_US', 'bogota', 'CO', 'US', 'culture'),
    ('lima_US', 'lima', 'PE', 'US', 'culture'),
    ('buenos_aires_US', 'buenos aires', 'AR', 'US', 'culture'),
    ('santiago_US', 'santiago', 'CL', 'US', 'culture'),
    ('manila_US', 'manila', 'PH', 'US', 'culture'),
    ('wadi_musa_US', 'wadi musa', 'JO', 'US', 'culture'),
    ('puerto_ayora_US', 'puerto ayora', 'EC', 'US', 'culture'),
    ('yulara_US', 'yulara', 'AU', 'US', 'culture'),
    ('yulara_SG', 'yulara', 'AU', 'SG', 'culture'),
    ('yulara_AU', 'yulara', 'AU', 'AU', 'culture'),
    ('yulara_IN', 'yulara', 'AU', 'IN', 'culture'),
    ('maun_US', 'maun', 'BW', 'US', 'culture'),
    ('jackson_US', 'jackson', 'US', 'US', 'culture'),
    ('jackson_SG', 'jackson', 'US', 'SG', 'culture'),
    ('jackson_AU', 'jackson', 'US', 'AU', 'culture'),
    ('jackson_IN', 'jackson', 'US', 'IN', 'culture'),
    ('bled_US', 'bled', 'SI', 'US', 'culture'),
    ('puerto_iguaz_US', 'puerto iguazú', 'BR', 'US', 'culture'),
    ('puerto_iguaz_SG', 'puerto iguazú', 'BR', 'SG', 'culture'),
    ('puerto_iguaz_AU', 'puerto iguazú', 'BR', 'AU', 'culture'),
    ('puerto_iguaz_IN', 'puerto iguazú', 'BR', 'IN', 'culture'),
    ('siem_reap_US', 'siem reap', 'KH', 'US', 'culture'),
    ('uyuni_US', 'uyuni', 'BO', 'US', 'culture'),
    ('pokhara_US', 'pokhara', 'NP', 'US', 'culture'),
    ('cairns_US', 'cairns', 'AU', 'US', 'culture'),
    ('cairns_SG', 'cairns', 'AU', 'SG', 'culture'),
    ('cairns_AU', 'cairns', 'AU', 'AU', 'culture'),
    ('cairns_IN', 'cairns', 'AU', 'IN', 'culture'),
    ('grand_canyon_village_US', 'grand canyon village', 'US', 'US', 'culture'),
    ('grand_canyon_village_SG', 'grand canyon village', 'US', 'SG', 'culture'),
    ('grand_canyon_village_AU', 'grand canyon village', 'US', 'AU', 'culture'),
    ('grand_canyon_village_IN', 'grand canyon village', 'US', 'IN', 'culture'),
    ('granada_US', 'granada', 'ES', 'US', 'culture'),
    ('granada_SG', 'granada', 'ES', 'SG', 'culture'),
    ('granada_AU', 'granada', 'ES', 'AU', 'culture'),
    ('granada_IN', 'granada', 'ES', 'IN', 'culture'),
    ('arusha_US', 'arusha', 'TZ', 'US', 'culture'),
    ('agra_US', 'agra', 'IN', 'US', 'culture'),
    ('agra_SG', 'agra', 'IN', 'SG', 'culture'),
    ('agra_AU', 'agra', 'IN', 'AU', 'culture'),
    ('agra_IN', 'agra', 'IN', 'IN', 'culture'),
    ('beijing_US', 'beijing', 'CN', 'US', 'culture'),
    ('havana_US', 'havana', 'CU', 'US', 'culture'),
    ('yosemite_valley_US', 'yosemite valley', 'US', 'US', 'culture'),
    ('yosemite_valley_SG', 'yosemite valley', 'US', 'SG', 'culture'),
    ('yosemite_valley_AU', 'yosemite valley', 'US', 'AU', 'culture'),
    ('yosemite_valley_IN', 'yosemite valley', 'US', 'IN', 'culture'),
    ('galway_US', 'galway', 'IE', 'US', 'culture'),
    ('fez_US', 'fez', 'MA', 'US', 'culture'),
    ('fez_SG', 'fez', 'MA', 'SG', 'culture'),
    ('fez_AU', 'fez', 'MA', 'AU', 'culture'),
    ('fez_IN', 'fez', 'MA', 'IN', 'culture'),
    ('amalfi_US', 'amalfi', 'IT', 'US', 'beach'),
    ('amalfi_SG', 'amalfi', 'IT', 'SG', 'beach'),
    ('amalfi_AU', 'amalfi', 'IT', 'AU', 'beach'),
    ('amalfi_IN', 'amalfi', 'IT', 'IN', 'beach'),
    ('cusco_US', 'cusco', 'PE', 'US', 'culture'),
    ('sydney_US', 'sydney', 'AU', 'US', 'culture'),
    ('sydney_SG', 'sydney', 'AU', 'SG', 'culture'),
    ('sydney_AU', 'sydney', 'AU', 'AU', 'culture'),
    ('sydney_IN', 'sydney', 'AU', 'IN', 'culture'),
    ('g_reme_US', 'göreme', 'TR', 'US', 'culture'),
    ('te_anau_US', 'te anau', 'NZ', 'US', 'culture'),
    ('te_anau_SG', 'te anau', 'NZ', 'SG', 'culture'),
    ('te_anau_AU', 'te anau', 'NZ', 'AU', 'culture'),
    ('te_anau_IN', 'te anau', 'NZ', 'IN', 'culture'),
    ('naples_US', 'naples', 'IT', 'US', 'culture'),
    ('naples_SG', 'naples', 'IT', 'SG', 'culture'),
    ('naples_AU', 'naples', 'IT', 'AU', 'culture'),
    ('naples_IN', 'naples', 'IT', 'IN', 'culture'),
    ('livingstone_US', 'livingstone', 'ZW', 'US', 'culture'),
    ('lake_louise_US', 'lake louise', 'CA', 'US', 'culture'),
    ('hoi_an_US', 'hoi an', 'VN', 'US', 'culture'),
    ('sintra_US', 'sintra', 'PT', 'US', 'culture'),
    ('sintra_SG', 'sintra', 'PT', 'SG', 'culture'),
    ('sintra_AU', 'sintra', 'PT', 'AU', 'culture'),
    ('sintra_IN', 'sintra', 'PT', 'IN', 'culture'),
    ('aqaba_US', 'aqaba', 'JO', 'US', 'beach'),
    ('san_pedro_de_atacama_US', 'san pedro de atacama', 'CL', 'US', 'culture'),
    ('flores_US', 'flores', 'GT', 'US', 'culture'),
    ('windermere_US', 'windermere', 'GB', 'US', 'culture'),
    ('windermere_SG', 'windermere', 'GB', 'SG', 'culture'),
    ('windermere_AU', 'windermere', 'GB', 'AU', 'culture'),
    ('windermere_IN', 'windermere', 'GB', 'IN', 'culture'),
    ('dunhuang_US', 'dunhuang', 'CN', 'US', 'culture'),
    ('waisai_US', 'waisai', 'ID', 'US', 'culture'),
    ('waisai_SG', 'waisai', 'ID', 'SG', 'culture'),
    ('waisai_AU', 'waisai', 'ID', 'AU', 'culture'),
    ('waisai_IN', 'waisai', 'ID', 'IN', 'culture'),
    ('kabale_US', 'kabale', 'UG', 'US', 'culture'),
    ('matera_US', 'matera', 'IT', 'US', 'culture'),
    ('matera_SG', 'matera', 'IT', 'SG', 'culture'),
    ('matera_AU', 'matera', 'IT', 'AU', 'culture'),
    ('matera_IN', 'matera', 'IT', 'IN', 'culture'),
    ('luxor_US', 'luxor', 'EG', 'US', 'culture'),
    ('svolvaer_US', 'svolvaer', 'NO', 'US', 'culture'),
    ('crescent_city_US', 'crescent city', 'US', 'US', 'culture'),
    ('crescent_city_SG', 'crescent city', 'US', 'SG', 'culture'),
    ('crescent_city_AU', 'crescent city', 'US', 'AU', 'culture'),
    ('crescent_city_IN', 'crescent city', 'US', 'IN', 'culture'),
    ('longyearbyen_US', 'longyearbyen', 'NO', 'US', 'culture'),
    ('jasper_US', 'jasper', 'CA', 'US', 'culture'),
    ('kawaguchiko_US', 'kawaguchiko', 'JP', 'US', 'culture'),
    ('kawaguchiko_SG', 'kawaguchiko', 'JP', 'SG', 'culture'),
    ('kawaguchiko_AU', 'kawaguchiko', 'JP', 'AU', 'culture'),
    ('kawaguchiko_IN', 'kawaguchiko', 'JP', 'IN', 'culture'),
    ('kochi_US', 'kochi', 'IN', 'US', 'culture'),
    ('kochi_SG', 'kochi', 'IN', 'SG', 'culture'),
    ('kochi_AU', 'kochi', 'IN', 'AU', 'culture'),
    ('kochi_IN', 'kochi', 'IN', 'IN', 'culture'),
    ('cape_town_US', 'cape town', 'ZA', 'US', 'culture'),
    ('cape_town_SG', 'cape town', 'ZA', 'SG', 'culture'),
    ('cape_town_AU', 'cape town', 'ZA', 'AU', 'culture'),
    ('cape_town_IN', 'cape town', 'ZA', 'IN', 'culture'),
    ('narok_US', 'narok', 'KE', 'US', 'culture'),
    ('lord_howe_island_US', 'lord howe island', 'AU', 'US', 'culture'),
    ('lord_howe_island_SG', 'lord howe island', 'AU', 'SG', 'culture'),
    ('lord_howe_island_AU', 'lord howe island', 'AU', 'AU', 'culture'),
    ('lord_howe_island_IN', 'lord howe island', 'AU', 'IN', 'culture'),
    ('puerto_natales_US', 'puerto natales', 'CL', 'US', 'culture'),
    ('budapest_US', 'budapest', 'HU', 'US', 'culture'),
    ('santorini_US', 'santorini', 'GR', 'US', 'culture'),
    ('santorini_SG', 'santorini', 'GR', 'SG', 'culture'),
    ('santorini_AU', 'santorini', 'GR', 'AU', 'culture'),
    ('santorini_IN', 'santorini', 'GR', 'IN', 'culture'),
    ('kayenta_US', 'kayenta', 'US', 'US', 'culture'),
    ('kayenta_SG', 'kayenta', 'US', 'SG', 'culture'),
    ('kayenta_AU', 'kayenta', 'US', 'AU', 'culture'),
    ('kayenta_IN', 'kayenta', 'US', 'IN', 'culture'),
    ('delhi_US', 'delhi', 'IN', 'US', 'culture'),
    ('delhi_SG', 'delhi', 'IN', 'SG', 'culture'),
    ('delhi_AU', 'delhi', 'IN', 'AU', 'culture'),
    ('delhi_IN', 'delhi', 'IN', 'IN', 'culture'),
    ('oswiecim_US', 'oswiecim', 'PL', 'US', 'culture'),
    ('yazd_US', 'yazd', 'IR', 'US', 'culture'),
    ('heraklion_US', 'heraklion', 'GR', 'US', 'culture'),
    ('heraklion_SG', 'heraklion', 'GR', 'SG', 'culture'),
    ('heraklion_AU', 'heraklion', 'GR', 'AU', 'culture'),
    ('heraklion_IN', 'heraklion', 'GR', 'IN', 'culture'),
    ('motueka_US', 'motueka', 'NZ', 'US', 'culture'),
    ('motueka_SG', 'motueka', 'NZ', 'SG', 'culture'),
    ('motueka_AU', 'motueka', 'NZ', 'AU', 'culture'),
    ('motueka_IN', 'motueka', 'NZ', 'IN', 'culture'),
    ('puerto_jimenez_US', 'puerto jimenez', 'CR', 'US', 'culture'),
    ('hilo_US', 'hilo', 'US', 'US', 'culture'),
    ('hilo_SG', 'hilo', 'US', 'SG', 'culture'),
    ('hilo_AU', 'hilo', 'US', 'AU', 'culture'),
    ('hilo_IN', 'hilo', 'US', 'IN', 'culture'),
    ('paro_US', 'paro', 'BT', 'US', 'culture'),
    ('fussen_US', 'fussen', 'DE', 'US', 'culture'),
    ('hofn_US', 'hofn', 'IS', 'US', 'culture'),
    ('mount_cook_village_US', 'mount cook village', 'NZ', 'US', 'culture'),
    ('mount_cook_village_SG', 'mount cook village', 'NZ', 'SG', 'culture'),
    ('mount_cook_village_AU', 'mount cook village', 'NZ', 'AU', 'culture'),
    ('mount_cook_village_IN', 'mount cook village', 'NZ', 'IN', 'culture'),
    ('cuiaba_US', 'cuiaba', 'BR', 'US', 'culture'),
    ('cuiaba_SG', 'cuiaba', 'BR', 'SG', 'culture'),
    ('cuiaba_AU', 'cuiaba', 'BR', 'AU', 'culture'),
    ('cuiaba_IN', 'cuiaba', 'BR', 'IN', 'culture'),
    ('cardiff_US', 'cardiff', 'GB', 'US', 'culture'),
    ('cardiff_SG', 'cardiff', 'GB', 'SG', 'culture'),
    ('cardiff_AU', 'cardiff', 'GB', 'AU', 'culture'),
    ('cardiff_IN', 'cardiff', 'GB', 'IN', 'culture'),
    ('shingu_US', 'shingu', 'JP', 'US', 'culture'),
    ('shingu_SG', 'shingu', 'JP', 'SG', 'culture'),
    ('shingu_AU', 'shingu', 'JP', 'AU', 'culture'),
    ('shingu_IN', 'shingu', 'JP', 'IN', 'culture'),
    ('embilipitiya_US', 'embilipitiya', 'LK', 'US', 'culture'),
    ('kotor_US', 'kotor', 'ME', 'US', 'culture'),
    ('giza_US', 'giza', 'EG', 'US', 'culture'),
    ('niagara_falls_US', 'niagara falls', 'CA', 'US', 'culture'),
    ('freiburg_US', 'freiburg', 'DE', 'US', 'culture'),
    ('magelang_US', 'magelang', 'ID', 'US', 'culture'),
    ('magelang_SG', 'magelang', 'ID', 'SG', 'culture'),
    ('magelang_AU', 'magelang', 'ID', 'AU', 'culture'),
    ('magelang_IN', 'magelang', 'ID', 'IN', 'culture'),
    ('kangaroo_island_US', 'kangaroo island', 'AU', 'US', 'culture'),
    ('kangaroo_island_SG', 'kangaroo island', 'AU', 'SG', 'culture'),
    ('kangaroo_island_AU', 'kangaroo island', 'AU', 'AU', 'culture'),
    ('kangaroo_island_IN', 'kangaroo island', 'AU', 'IN', 'culture'),
    ('rovaniemi_US', 'rovaniemi', 'FI', 'US', 'culture'),
    ('cangas_de_onis_US', 'cangas de onis', 'ES', 'US', 'culture'),
    ('cangas_de_onis_SG', 'cangas de onis', 'ES', 'SG', 'culture'),
    ('cangas_de_onis_AU', 'cangas de onis', 'ES', 'AU', 'culture'),
    ('cangas_de_onis_IN', 'cangas de onis', 'ES', 'IN', 'culture'),
    ('coles_bay_US', 'coles bay', 'AU', 'US', 'culture'),
    ('coles_bay_SG', 'coles bay', 'AU', 'SG', 'culture'),
    ('coles_bay_AU', 'coles bay', 'AU', 'AU', 'culture'),
    ('coles_bay_IN', 'coles bay', 'AU', 'IN', 'culture'),
    ('baalbek_US', 'baalbek', 'LB', 'US', 'culture'),
    ('lhasa_US', 'lhasa', 'CN', 'US', 'culture'),
    ('ilulissat_US', 'ilulissat', 'GL', 'US', 'culture'),
    ('siena_US', 'siena', 'IT', 'US', 'culture'),
    ('siena_SG', 'siena', 'IT', 'SG', 'culture'),
    ('siena_AU', 'siena', 'IT', 'AU', 'culture'),
    ('siena_IN', 'siena', 'IT', 'IN', 'culture'),
    ('naoshima_US', 'naoshima', 'JP', 'US', 'culture'),
    ('naoshima_SG', 'naoshima', 'JP', 'SG', 'culture'),
    ('naoshima_AU', 'naoshima', 'JP', 'AU', 'culture'),
    ('naoshima_IN', 'naoshima', 'JP', 'IN', 'culture'),
    ('samarkand_US', 'samarkand', 'UZ', 'US', 'culture'),
    ('bushmills_US', 'bushmills', 'GB', 'US', 'culture'),
    ('bushmills_SG', 'bushmills', 'GB', 'SG', 'culture'),
    ('bushmills_AU', 'bushmills', 'GB', 'AU', 'culture'),
    ('bushmills_IN', 'bushmills', 'GB', 'IN', 'culture'),
    ('abu_dhabi_US', 'abu dhabi', 'AE', 'US', 'culture'),
    ('abu_dhabi_SG', 'abu dhabi', 'AE', 'SG', 'culture'),
    ('abu_dhabi_AU', 'abu dhabi', 'AE', 'AU', 'culture'),
    ('abu_dhabi_IN', 'abu dhabi', 'AE', 'IN', 'culture'),
    ('amritsar_US', 'amritsar', 'IN', 'US', 'culture'),
    ('amritsar_SG', 'amritsar', 'IN', 'SG', 'culture'),
    ('amritsar_AU', 'amritsar', 'IN', 'AU', 'culture'),
    ('amritsar_IN', 'amritsar', 'IN', 'IN', 'culture'),
    ('washington_US', 'washington', 'US', 'US', 'culture'),
    ('washington_SG', 'washington', 'US', 'SG', 'culture'),
    ('washington_AU', 'washington', 'US', 'AU', 'culture'),
    ('washington_IN', 'washington', 'US', 'IN', 'culture'),
    ('zermatt_US', 'zermatt', 'CH', 'US', 'culture'),
    ('gilgit_US', 'gilgit', 'PK', 'US', 'culture'),
    ('skukuza_US', 'skukuza', 'ZA', 'US', 'culture'),
    ('skukuza_SG', 'skukuza', 'ZA', 'SG', 'culture'),
    ('skukuza_AU', 'skukuza', 'ZA', 'AU', 'culture'),
    ('skukuza_IN', 'skukuza', 'ZA', 'IN', 'culture'),
    ('purmamarca_US', 'purmamarca', 'AR', 'US', 'culture'),
    ('florence_US', 'florence', 'IT', 'US', 'culture'),
    ('florence_SG', 'florence', 'IT', 'SG', 'culture'),
    ('florence_AU', 'florence', 'IT', 'AU', 'culture'),
    ('florence_IN', 'florence', 'IT', 'IN', 'culture'),
    ('koya_US', 'koya', 'JP', 'US', 'culture'),
    ('koya_SG', 'koya', 'JP', 'SG', 'culture'),
    ('koya_AU', 'koya', 'JP', 'AU', 'culture'),
    ('koya_IN', 'koya', 'JP', 'IN', 'culture'),
    ('killarney_US', 'killarney', 'IE', 'US', 'culture'),
    ('fernando_de_noronha_US', 'fernando de noronha', 'BR', 'US', 'culture'),
    ('fernando_de_noronha_SG', 'fernando de noronha', 'BR', 'SG', 'culture'),
    ('fernando_de_noronha_AU', 'fernando de noronha', 'BR', 'AU', 'culture'),
    ('fernando_de_noronha_IN', 'fernando de noronha', 'BR', 'IN', 'culture'),
    ('bournemouth_US', 'bournemouth', 'GB', 'US', 'culture'),
    ('bournemouth_SG', 'bournemouth', 'GB', 'SG', 'culture'),
    ('bournemouth_AU', 'bournemouth', 'GB', 'AU', 'culture'),
    ('bournemouth_IN', 'bournemouth', 'GB', 'IN', 'culture'),
    ('safj_r_ur_US', 'ísafjörður', 'IS', 'US', 'culture'),
    ('interlaken_US', 'interlaken', 'CH', 'US', 'culture'),
    ('cartagena_US', 'cartagena', 'CO', 'US', 'culture'),
    ('nuwara_eliya_US', 'nuwara eliya', 'LK', 'US', 'culture'),
    ('talkeetna_US', 'talkeetna', 'US', 'US', 'culture'),
    ('talkeetna_SG', 'talkeetna', 'US', 'SG', 'culture'),
    ('talkeetna_AU', 'talkeetna', 'US', 'AU', 'culture'),
    ('talkeetna_IN', 'talkeetna', 'US', 'IN', 'culture'),
    ('khorog_US', 'khorog', 'TJ', 'US', 'culture'),
    ('kaikoura_US', 'kaikoura', 'NZ', 'US', 'culture'),
    ('kaikoura_SG', 'kaikoura', 'NZ', 'SG', 'culture'),
    ('kaikoura_AU', 'kaikoura', 'NZ', 'AU', 'culture'),
    ('kaikoura_IN', 'kaikoura', 'NZ', 'IN', 'culture'),
    ('valladolid_US', 'valladolid', 'MX', 'US', 'culture'),
    ('valladolid_SG', 'valladolid', 'MX', 'SG', 'culture'),
    ('valladolid_AU', 'valladolid', 'MX', 'AU', 'culture'),
    ('valladolid_IN', 'valladolid', 'MX', 'IN', 'culture'),
    ('plitvice_lakes_US', 'plitvice lakes', 'HR', 'US', 'culture'),
    ('plitvice_lakes_SG', 'plitvice lakes', 'HR', 'SG', 'culture'),
    ('plitvice_lakes_AU', 'plitvice lakes', 'HR', 'AU', 'culture'),
    ('plitvice_lakes_IN', 'plitvice lakes', 'HR', 'IN', 'culture'),
    ('versailles_US', 'versailles', 'FR', 'US', 'culture'),
    ('versailles_SG', 'versailles', 'FR', 'SG', 'culture'),
    ('versailles_AU', 'versailles', 'FR', 'AU', 'culture'),
    ('versailles_IN', 'versailles', 'FR', 'IN', 'culture'),
    ('shiraz_US', 'shiraz', 'IR', 'US', 'culture'),
    ('dambulla_US', 'dambulla', 'LK', 'US', 'culture'),
    ('bruges_US', 'bruges', 'BE', 'US', 'culture'),
    ('jaisalmer_US', 'jaisalmer', 'IN', 'US', 'culture'),
    ('jaisalmer_SG', 'jaisalmer', 'IN', 'SG', 'culture'),
    ('jaisalmer_AU', 'jaisalmer', 'IN', 'AU', 'culture'),
    ('jaisalmer_IN', 'jaisalmer', 'IN', 'IN', 'culture'),
    ('khao_lak_US', 'khao lak', 'TH', 'US', 'beach'),
    ('khao_lak_SG', 'khao lak', 'TH', 'SG', 'beach'),
    ('khao_lak_AU', 'khao lak', 'TH', 'AU', 'beach'),
    ('khao_lak_IN', 'khao lak', 'TH', 'IN', 'beach'),
    ('karoi_US', 'karoi', 'ZW', 'US', 'culture'),
    ('xi_an_US', 'xi\'an', 'CN', 'US', 'culture'),
    ('mangochi_US', 'mangochi', 'MW', 'US', 'culture'),
    ('abu_simbel_US', 'abu simbel', 'EG', 'US', 'culture'),
    ('mcmurdo_station_US', 'mcmurdo station', 'AQ', 'US', 'culture'),
    ('amman_US', 'amman', 'JO', 'US', 'culture'),
    ('marrakech_US', 'marrakech', 'MA', 'US', 'culture'),
    ('marrakech_SG', 'marrakech', 'MA', 'SG', 'culture'),
    ('marrakech_AU', 'marrakech', 'MA', 'AU', 'culture'),
    ('marrakech_IN', 'marrakech', 'MA', 'IN', 'culture'),
    ('fethiye_US', 'fethiye', 'TR', 'US', 'beach'),
    ('mekele_US', 'mekele', 'ET', 'US', 'culture'),
    ('ararat_US', 'ararat', 'AU', 'US', 'culture'),
    ('ararat_SG', 'ararat', 'AU', 'SG', 'culture'),
    ('ararat_AU', 'ararat', 'AU', 'AU', 'culture'),
    ('ararat_IN', 'ararat', 'AU', 'IN', 'culture'),
    ('exmouth_US', 'exmouth', 'AU', 'US', 'culture'),
    ('exmouth_SG', 'exmouth', 'AU', 'SG', 'culture'),
    ('exmouth_AU', 'exmouth', 'AU', 'AU', 'culture'),
    ('exmouth_IN', 'exmouth', 'AU', 'IN', 'culture'),
    ('furnace_creek_US', 'furnace creek', 'US', 'US', 'culture'),
    ('furnace_creek_SG', 'furnace creek', 'US', 'SG', 'culture'),
    ('furnace_creek_AU', 'furnace creek', 'US', 'AU', 'culture'),
    ('furnace_creek_IN', 'furnace creek', 'US', 'IN', 'culture'),
    ('stykkisholmur_US', 'stykkisholmur', 'IS', 'US', 'culture'),
    ('brecon_US', 'brecon', 'GB', 'US', 'culture'),
    ('brecon_SG', 'brecon', 'GB', 'SG', 'culture'),
    ('brecon_AU', 'brecon', 'GB', 'AU', 'culture'),
    ('brecon_IN', 'brecon', 'GB', 'IN', 'culture'),
    ('canc_n_US', 'cancún', 'MX', 'US', 'culture'),
    ('canc_n_SG', 'cancún', 'MX', 'SG', 'culture'),
    ('canc_n_AU', 'cancún', 'MX', 'AU', 'culture'),
    ('canc_n_IN', 'cancún', 'MX', 'IN', 'culture'),
    ('lisbon_US', 'lisbon', 'PT', 'US', 'culture'),
    ('lisbon_SG', 'lisbon', 'PT', 'SG', 'culture'),
    ('lisbon_AU', 'lisbon', 'PT', 'AU', 'culture'),
    ('lisbon_IN', 'lisbon', 'PT', 'IN', 'culture'),
    ('surat_thani_US', 'surat thani', 'TH', 'US', 'beach'),
    ('surat_thani_SG', 'surat thani', 'TH', 'SG', 'beach'),
    ('surat_thani_AU', 'surat thani', 'TH', 'AU', 'beach'),
    ('surat_thani_IN', 'surat thani', 'TH', 'IN', 'beach'),
    ('arequipa_US', 'arequipa', 'PE', 'US', 'culture'),
    ('inhambane_US', 'inhambane', 'MZ', 'US', 'culture'),
    ('caernarfon_US', 'caernarfon', 'GB', 'US', 'culture'),
    ('caernarfon_SG', 'caernarfon', 'GB', 'SG', 'culture'),
    ('caernarfon_AU', 'caernarfon', 'GB', 'AU', 'culture'),
    ('caernarfon_IN', 'caernarfon', 'GB', 'IN', 'culture'),
    ('clifden_US', 'clifden', 'IE', 'US', 'culture'),
    ('cordoba_US', 'cordoba', 'ES', 'US', 'culture'),
    ('cordoba_SG', 'cordoba', 'ES', 'SG', 'culture'),
    ('cordoba_AU', 'cordoba', 'ES', 'AU', 'culture'),
    ('cordoba_IN', 'cordoba', 'ES', 'IN', 'culture'),
    ('sesriem_US', 'sesriem', 'NA', 'US', 'culture'),
    ('ravenna_US', 'ravenna', 'IT', 'US', 'culture'),
    ('ravenna_SG', 'ravenna', 'IT', 'SG', 'culture'),
    ('ravenna_AU', 'ravenna', 'IT', 'AU', 'culture'),
    ('ravenna_IN', 'ravenna', 'IT', 'IN', 'culture'),
    ('quebec_city_US', 'quebec city', 'CA', 'US', 'culture'),
    ('fort_william_US', 'fort william', 'GB', 'US', 'culture'),
    ('fort_william_SG', 'fort william', 'GB', 'SG', 'culture'),
    ('fort_william_AU', 'fort william', 'GB', 'AU', 'culture'),
    ('fort_william_IN', 'fort william', 'GB', 'IN', 'culture'),
    ('v_k_US', 'vík', 'IS', 'US', 'culture'),
    ('bora_bora_US', 'bora bora', 'PF', 'US', 'beach'),
    ('rivas_US', 'rivas', 'NI', 'US', 'culture'),
    ('puerto_madryn_US', 'puerto madryn', 'AR', 'US', 'culture'),
    ('prague_US', 'prague', 'CZ', 'US', 'culture'),
    ('harbin_US', 'harbin', 'CN', 'US', 'culture'),
    ('mont_saint_michel_US', 'mont-saint-michel', 'FR', 'US', 'culture'),
    ('mont_saint_michel_SG', 'mont-saint-michel', 'FR', 'SG', 'culture'),
    ('mont_saint_michel_AU', 'mont-saint-michel', 'FR', 'AU', 'culture'),
    ('mont_saint_michel_IN', 'mont-saint-michel', 'FR', 'IN', 'culture'),
    ('como_US', 'como', 'IT', 'US', 'culture'),
    ('como_SG', 'como', 'IT', 'SG', 'culture'),
    ('como_AU', 'como', 'IT', 'AU', 'culture'),
    ('como_IN', 'como', 'IT', 'IN', 'culture'),
    ('seville_US', 'seville', 'ES', 'US', 'culture'),
    ('seville_SG', 'seville', 'ES', 'SG', 'culture'),
    ('seville_AU', 'seville', 'ES', 'AU', 'culture'),
    ('seville_IN', 'seville', 'ES', 'IN', 'culture'),
    ('palenque_US', 'palenque', 'MX', 'US', 'culture'),
    ('palenque_SG', 'palenque', 'MX', 'SG', 'culture'),
    ('palenque_AU', 'palenque', 'MX', 'AU', 'culture'),
    ('palenque_IN', 'palenque', 'MX', 'IN', 'culture'),
    ('isfahan_US', 'isfahan', 'IR', 'US', 'culture'),
    ('orlando_US', 'orlando', 'US', 'US', 'culture'),
    ('orlando_SG', 'orlando', 'US', 'SG', 'culture'),
    ('orlando_AU', 'orlando', 'US', 'AU', 'culture'),
    ('orlando_IN', 'orlando', 'US', 'IN', 'culture'),
    ('russell_US', 'russell', 'NZ', 'US', 'culture'),
    ('russell_SG', 'russell', 'NZ', 'SG', 'culture'),
    ('russell_AU', 'russell', 'NZ', 'AU', 'culture'),
    ('russell_IN', 'russell', 'NZ', 'IN', 'culture'),
    ('vienna_US', 'vienna', 'AT', 'US', 'culture'),
    ('moorea_US', 'moorea', 'PF', 'US', 'beach'),
    ('n_mes_US', 'nîmes', 'FR', 'US', 'culture'),
    ('n_mes_SG', 'nîmes', 'FR', 'SG', 'culture'),
    ('n_mes_AU', 'nîmes', 'FR', 'AU', 'culture'),
    ('n_mes_IN', 'nîmes', 'FR', 'IN', 'culture'),
    ('cologne_US', 'cologne', 'DE', 'US', 'culture'),
    ('agrigento_US', 'agrigento', 'IT', 'US', 'culture'),
    ('agrigento_SG', 'agrigento', 'IT', 'SG', 'culture'),
    ('agrigento_AU', 'agrigento', 'IT', 'AU', 'culture'),
    ('agrigento_IN', 'agrigento', 'IT', 'IN', 'culture'),
    ('squamish_US', 'squamish', 'CA', 'US', 'culture'),
    ('nara_US', 'nara', 'JP', 'US', 'culture'),
    ('nara_SG', 'nara', 'JP', 'SG', 'culture'),
    ('nara_AU', 'nara', 'JP', 'AU', 'culture'),
    ('nara_IN', 'nara', 'JP', 'IN', 'culture'),
    ('nazca_US', 'nazca', 'PE', 'US', 'culture'),
    ('morondava_US', 'morondava', 'MG', 'US', 'culture'),
    ('el_calafate_US', 'el calafate', 'AR', 'US', 'culture'),
    ('swakopmund_US', 'swakopmund', 'NA', 'US', 'culture'),
    ('hualien_US', 'hualien', 'TW', 'US', 'culture'),
    ('waitomo_US', 'waitomo', 'NZ', 'US', 'culture'),
    ('waitomo_SG', 'waitomo', 'NZ', 'SG', 'culture'),
    ('waitomo_AU', 'waitomo', 'NZ', 'AU', 'culture'),
    ('waitomo_IN', 'waitomo', 'NZ', 'IN', 'culture'),
    ('wanaka_US', 'wanaka', 'NZ', 'US', 'culture'),
    ('wanaka_SG', 'wanaka', 'NZ', 'SG', 'culture'),
    ('wanaka_AU', 'wanaka', 'NZ', 'AU', 'culture'),
    ('wanaka_IN', 'wanaka', 'NZ', 'IN', 'culture'),
    ('glencoe_US', 'glencoe', 'GB', 'US', 'culture'),
    ('glencoe_SG', 'glencoe', 'GB', 'SG', 'culture'),
    ('glencoe_AU', 'glencoe', 'GB', 'AU', 'culture'),
    ('glencoe_IN', 'glencoe', 'GB', 'IN', 'culture'),
    ('belize_city_US', 'belize city', 'BZ', 'US', 'culture'),
    ('santa_cruz_de_tenerife_US', 'santa cruz de tenerife', 'ES', 'US', 'culture'),
    ('santa_cruz_de_tenerife_SG', 'santa cruz de tenerife', 'ES', 'SG', 'culture'),
    ('santa_cruz_de_tenerife_AU', 'santa cruz de tenerife', 'ES', 'AU', 'culture'),
    ('santa_cruz_de_tenerife_IN', 'santa cruz de tenerife', 'ES', 'IN', 'culture'),
    ('darchen_US', 'darchen', 'CN', 'US', 'culture'),
    ('outjo_US', 'outjo', 'NA', 'US', 'culture'),
    ('eastbourne_US', 'eastbourne', 'GB', 'US', 'culture'),
    ('eastbourne_SG', 'eastbourne', 'GB', 'SG', 'culture'),
    ('eastbourne_AU', 'eastbourne', 'GB', 'AU', 'culture'),
    ('eastbourne_IN', 'eastbourne', 'GB', 'IN', 'culture'),
    ('cortez_US', 'cortez', 'US', 'US', 'culture'),
    ('cortez_SG', 'cortez', 'US', 'SG', 'culture'),
    ('cortez_AU', 'cortez', 'US', 'AU', 'culture'),
    ('cortez_IN', 'cortez', 'US', 'IN', 'culture'),
    ('dana_US', 'dana', 'JO', 'US', 'culture'),
    ('dakar_US', 'dakar', 'SN', 'US', 'culture'),
    ('paju_US', 'paju', 'KR', 'US', 'culture'),
    ('balloch_US', 'balloch', 'GB', 'US', 'culture'),
    ('balloch_SG', 'balloch', 'GB', 'SG', 'culture'),
    ('balloch_AU', 'balloch', 'GB', 'AU', 'culture'),
    ('balloch_IN', 'balloch', 'GB', 'IN', 'culture'),
    ('zagora_US', 'zagora', 'MA', 'US', 'culture'),
    ('zagora_SG', 'zagora', 'MA', 'SG', 'culture'),
    ('zagora_AU', 'zagora', 'MA', 'AU', 'culture'),
    ('zagora_IN', 'zagora', 'MA', 'IN', 'culture'),
    ('salisbury_US', 'salisbury', 'GB', 'US', 'culture'),
    ('salisbury_SG', 'salisbury', 'GB', 'SG', 'culture'),
    ('salisbury_AU', 'salisbury', 'GB', 'AU', 'culture'),
    ('salisbury_IN', 'salisbury', 'GB', 'IN', 'culture'),
    ('tallinn_US', 'tallinn', 'EE', 'US', 'culture'),
    ('zernez_US', 'zernez', 'CH', 'US', 'culture'),
    ('nampula_US', 'nampula', 'MZ', 'US', 'culture'),
    ('hanga_roa_US', 'hanga roa', 'CL', 'US', 'culture'),
    ('panajachel_US', 'panajachel', 'GT', 'US', 'culture'),
    ('taos_US', 'taos', 'US', 'US', 'culture'),
    ('taos_SG', 'taos', 'US', 'SG', 'culture'),
    ('taos_AU', 'taos', 'US', 'AU', 'culture'),
    ('taos_IN', 'taos', 'US', 'IN', 'culture'),
    ('queen_charlotte_US', 'queen charlotte', 'CA', 'US', 'culture'),
    ('selcuk_US', 'selcuk', 'TR', 'US', 'culture'),
    ('las_vegas_US', 'las vegas', 'US', 'US', 'culture'),
    ('las_vegas_SG', 'las vegas', 'US', 'SG', 'culture'),
    ('las_vegas_AU', 'las vegas', 'US', 'AU', 'culture'),
    ('las_vegas_IN', 'las vegas', 'US', 'IN', 'culture'),
    ('manzini_US', 'manzini', 'SZ', 'US', 'culture'),
    ('kirkwall_US', 'kirkwall', 'GB', 'US', 'culture'),
    ('kirkwall_SG', 'kirkwall', 'GB', 'SG', 'culture'),
    ('kirkwall_AU', 'kirkwall', 'GB', 'AU', 'culture'),
    ('kirkwall_IN', 'kirkwall', 'GB', 'IN', 'culture'),
    ('blantyre_US', 'blantyre', 'MW', 'US', 'culture'),
    ('corrientes_US', 'corrientes', 'AR', 'US', 'culture'),
    ('dubrovnik_US', 'dubrovnik', 'HR', 'US', 'beach'),
    ('dubrovnik_SG', 'dubrovnik', 'HR', 'SG', 'beach'),
    ('dubrovnik_AU', 'dubrovnik', 'HR', 'AU', 'beach'),
    ('dubrovnik_IN', 'dubrovnik', 'HR', 'IN', 'beach'),
    ('andalsnes_US', 'andalsnes', 'NO', 'US', 'culture'),
    ('halong_city_US', 'halong city', 'VN', 'US', 'culture'),
    ('almaty_US', 'almaty', 'KZ', 'US', 'culture'),
    ('ayutthaya_US', 'ayutthaya', 'TH', 'US', 'culture'),
    ('ayutthaya_SG', 'ayutthaya', 'TH', 'SG', 'culture'),
    ('ayutthaya_AU', 'ayutthaya', 'TH', 'AU', 'culture'),
    ('ayutthaya_IN', 'ayutthaya', 'TH', 'IN', 'culture'),
    ('huaraz_US', 'huaraz', 'PE', 'US', 'culture'),
    ('edinburgh_US', 'edinburgh', 'GB', 'US', 'culture'),
    ('edinburgh_SG', 'edinburgh', 'GB', 'SG', 'culture'),
    ('edinburgh_AU', 'edinburgh', 'GB', 'AU', 'culture'),
    ('edinburgh_IN', 'edinburgh', 'GB', 'IN', 'culture'),
    ('ho_chi_minh_city_US', 'ho chi minh city', 'VN', 'US', 'culture'),
    ('vinales_US', 'vinales', 'CU', 'US', 'culture'),
    ('zagreb_US', 'zagreb', 'HR', 'US', 'culture'),
    ('zagreb_SG', 'zagreb', 'HR', 'SG', 'culture'),
    ('zagreb_AU', 'zagreb', 'HR', 'AU', 'culture'),
    ('zagreb_IN', 'zagreb', 'HR', 'IN', 'culture'),
    ('leh_US', 'leh', 'IN', 'US', 'culture'),
    ('leh_SG', 'leh', 'IN', 'SG', 'culture'),
    ('leh_AU', 'leh', 'IN', 'AU', 'culture'),
    ('leh_IN', 'leh', 'IN', 'IN', 'culture'),
    ('mfuwe_US', 'mfuwe', 'ZM', 'US', 'culture'),
    ('kigoma_US', 'kigoma', 'TZ', 'US', 'culture'),
    ('chamonix_US', 'chamonix', 'FR', 'US', 'culture'),
    ('chamonix_SG', 'chamonix', 'FR', 'SG', 'culture'),
    ('chamonix_AU', 'chamonix', 'FR', 'AU', 'culture'),
    ('chamonix_IN', 'chamonix', 'FR', 'IN', 'culture'),
    ('kars_US', 'kars', 'TR', 'US', 'culture'),
    ('lalomanu_US', 'lalomanu', 'WS', 'US', 'culture'),
    ('luang_namtha_US', 'luang namtha', 'LA', 'US', 'culture'),
    ('coromandel_US', 'coromandel', 'NZ', 'US', 'culture'),
    ('coromandel_SG', 'coromandel', 'NZ', 'SG', 'culture'),
    ('coromandel_AU', 'coromandel', 'NZ', 'AU', 'culture'),
    ('coromandel_IN', 'coromandel', 'NZ', 'IN', 'culture'),
    ('lanqu_n_US', 'lanquín', 'GT', 'US', 'culture'),
    ('bra_ov_US', 'brașov', 'RO', 'US', 'culture'),
    ('billund_US', 'billund', 'DK', 'US', 'culture'),
    ('drogheda_US', 'drogheda', 'IE', 'US', 'culture'),
    ('el_nido_US', 'el nido', 'PH', 'US', 'beach'),
    ('bath_US', 'bath', 'GB', 'US', 'culture'),
    ('bath_SG', 'bath', 'GB', 'SG', 'culture'),
    ('bath_AU', 'bath', 'GB', 'AU', 'culture'),
    ('bath_IN', 'bath', 'GB', 'IN', 'culture'),
    ('sam_neua_US', 'sam neua', 'LA', 'US', 'culture'),
    ('rurrenabaque_US', 'rurrenabaque', 'BO', 'US', 'culture'),
    ('kutn_hora_US', 'kutná hora', 'CZ', 'US', 'culture'),
    ('cairo_US', 'cairo', 'EG', 'US', 'culture'),
    ('tulcea_US', 'tulcea', 'RO', 'US', 'culture'),
    ('alberobello_US', 'alberobello', 'IT', 'US', 'culture'),
    ('alberobello_SG', 'alberobello', 'IT', 'SG', 'culture'),
    ('alberobello_AU', 'alberobello', 'IT', 'AU', 'culture'),
    ('alberobello_IN', 'alberobello', 'IT', 'IN', 'culture'),
    ('varanasi_US', 'varanasi', 'IN', 'US', 'culture'),
    ('varanasi_SG', 'varanasi', 'IN', 'SG', 'culture'),
    ('varanasi_AU', 'varanasi', 'IN', 'AU', 'culture'),
    ('varanasi_IN', 'varanasi', 'IN', 'IN', 'culture'),
    ('kalambaka_US', 'kalambaka', 'GR', 'US', 'culture'),
    ('kalambaka_SG', 'kalambaka', 'GR', 'SG', 'culture'),
    ('kalambaka_AU', 'kalambaka', 'GR', 'AU', 'culture'),
    ('kalambaka_IN', 'kalambaka', 'GR', 'IN', 'culture'),
    ('drumheller_US', 'drumheller', 'CA', 'US', 'culture'),
    ('limon_US', 'limon', 'CR', 'US', 'culture'),
    ('venice_US', 'venice', 'IT', 'US', 'culture'),
    ('venice_SG', 'venice', 'IT', 'SG', 'culture'),
    ('venice_AU', 'venice', 'IT', 'AU', 'culture'),
    ('venice_IN', 'venice', 'IT', 'IN', 'culture'),
    ('bayeux_US', 'bayeux', 'FR', 'US', 'culture'),
    ('bayeux_SG', 'bayeux', 'FR', 'SG', 'culture'),
    ('bayeux_AU', 'bayeux', 'FR', 'AU', 'culture'),
    ('bayeux_IN', 'bayeux', 'FR', 'IN', 'culture'),
    ('jaipur_US', 'jaipur', 'IN', 'US', 'culture'),
    ('jaipur_SG', 'jaipur', 'IN', 'SG', 'culture'),
    ('jaipur_AU', 'jaipur', 'IN', 'AU', 'culture'),
    ('jaipur_IN', 'jaipur', 'IN', 'IN', 'culture'),
    ('khatgal_US', 'khatgal', 'MN', 'US', 'culture'),
    ('seoul_US', 'seoul', 'KR', 'US', 'culture'),
    ('bacalar_US', 'bacalar', 'MX', 'US', 'culture'),
    ('bacalar_SG', 'bacalar', 'MX', 'SG', 'culture'),
    ('bacalar_AU', 'bacalar', 'MX', 'AU', 'culture'),
    ('bacalar_IN', 'bacalar', 'MX', 'IN', 'culture'),
    ('la_macarena_US', 'la macarena', 'CO', 'US', 'culture'),
    ('joshimath_US', 'joshimath', 'IN', 'US', 'culture'),
    ('joshimath_SG', 'joshimath', 'IN', 'SG', 'culture'),
    ('joshimath_AU', 'joshimath', 'IN', 'AU', 'culture'),
    ('joshimath_IN', 'joshimath', 'IN', 'IN', 'culture'),
    ('shanghai_US', 'shanghai', 'CN', 'US', 'culture'),
    ('aurangabad_US', 'aurangabad', 'IN', 'US', 'culture'),
    ('aurangabad_SG', 'aurangabad', 'IN', 'SG', 'culture'),
    ('aurangabad_AU', 'aurangabad', 'IN', 'AU', 'culture'),
    ('aurangabad_IN', 'aurangabad', 'IN', 'IN', 'culture'),
    ('kathmandu_US', 'kathmandu', 'NP', 'US', 'culture'),
    ('johannesburg_US', 'johannesburg', 'ZA', 'US', 'culture'),
    ('johannesburg_SG', 'johannesburg', 'ZA', 'SG', 'culture'),
    ('johannesburg_AU', 'johannesburg', 'ZA', 'AU', 'culture'),
    ('johannesburg_IN', 'johannesburg', 'ZA', 'IN', 'culture'),
    ('saint_john_US', 'saint john', 'CA', 'US', 'culture'),
    ('krakow_US', 'krakow', 'PL', 'US', 'culture'),
    ('saint_pierre_US', 'saint-pierre', 'FR', 'US', 'culture'),
    ('saint_pierre_SG', 'saint-pierre', 'FR', 'SG', 'culture'),
    ('saint_pierre_AU', 'saint-pierre', 'FR', 'AU', 'culture'),
    ('saint_pierre_IN', 'saint-pierre', 'FR', 'IN', 'culture'),
    ('inverness_US', 'inverness', 'GB', 'US', 'culture'),
    ('inverness_SG', 'inverness', 'GB', 'SG', 'culture'),
    ('inverness_AU', 'inverness', 'GB', 'AU', 'culture'),
    ('inverness_IN', 'inverness', 'GB', 'IN', 'culture'),
    ('phang_nga_US', 'phang nga', 'TH', 'US', 'culture'),
    ('phang_nga_SG', 'phang nga', 'TH', 'SG', 'culture'),
    ('phang_nga_AU', 'phang nga', 'TH', 'AU', 'culture'),
    ('phang_nga_IN', 'phang nga', 'TH', 'IN', 'culture'),
    ('puno_US', 'puno', 'PE', 'US', 'culture'),
    ('split_US', 'split', 'HR', 'US', 'culture'),
    ('split_SG', 'split', 'HR', 'SG', 'culture'),
    ('split_AU', 'split', 'HR', 'AU', 'culture'),
    ('split_IN', 'split', 'HR', 'IN', 'culture'),
    ('madrid_US', 'madrid', 'ES', 'US', 'culture'),
    ('madrid_SG', 'madrid', 'ES', 'SG', 'culture'),
    ('madrid_AU', 'madrid', 'ES', 'AU', 'culture'),
    ('madrid_IN', 'madrid', 'ES', 'IN', 'culture'),
    ('postojna_US', 'postojna', 'SI', 'US', 'culture'),
    ('champasak_US', 'champasak', 'LA', 'US', 'culture'),
    ('chandrapur_US', 'chandrapur', 'IN', 'US', 'culture'),
    ('chandrapur_SG', 'chandrapur', 'IN', 'SG', 'culture'),
    ('chandrapur_AU', 'chandrapur', 'IN', 'AU', 'culture'),
    ('chandrapur_IN', 'chandrapur', 'IN', 'IN', 'culture'),
    ('arles_US', 'arles', 'FR', 'US', 'culture'),
    ('arles_SG', 'arles', 'FR', 'SG', 'culture'),
    ('arles_AU', 'arles', 'FR', 'AU', 'culture'),
    ('arles_IN', 'arles', 'FR', 'IN', 'culture'),
    ('belmopan_US', 'belmopan', 'BZ', 'US', 'culture'),
    ('batna_US', 'batna', 'DZ', 'US', 'culture'),
    ('oxford_US', 'oxford', 'GB', 'US', 'culture'),
    ('oxford_SG', 'oxford', 'GB', 'SG', 'culture'),
    ('oxford_AU', 'oxford', 'GB', 'AU', 'culture'),
    ('oxford_IN', 'oxford', 'GB', 'IN', 'culture'),
    ('saranda_US', 'saranda', 'AL', 'US', 'culture'),
    ('namche_bazaar_US', 'namche bazaar', 'NP', 'US', 'culture'),
    ('novi_pazar_US', 'novi pazar', 'RS', 'US', 'culture'),
    ('tunis_US', 'tunis', 'TN', 'US', 'culture'),
    ('hong_kong_US', 'hong kong', 'CN', 'US', 'culture'),
    ('brasilia_US', 'brasilia', 'BR', 'US', 'culture'),
    ('brasilia_SG', 'brasilia', 'BR', 'SG', 'culture'),
    ('brasilia_AU', 'brasilia', 'BR', 'AU', 'culture'),
    ('brasilia_IN', 'brasilia', 'BR', 'IN', 'culture'),
    ('nairobi_US', 'nairobi', 'KE', 'US', 'culture'),
    ('santiago_de_compostela_US', 'santiago de compostela', 'ES', 'US', 'culture'),
    ('santiago_de_compostela_SG', 'santiago de compostela', 'ES', 'SG', 'culture'),
    ('santiago_de_compostela_AU', 'santiago de compostela', 'ES', 'AU', 'culture'),
    ('santiago_de_compostela_IN', 'santiago de compostela', 'ES', 'IN', 'culture'),
    ('mostar_US', 'mostar', 'BA', 'US', 'culture'),
    ('rotorua_US', 'rotorua', 'NZ', 'US', 'culture'),
    ('rotorua_SG', 'rotorua', 'NZ', 'SG', 'culture'),
    ('rotorua_AU', 'rotorua', 'NZ', 'AU', 'culture'),
    ('rotorua_IN', 'rotorua', 'NZ', 'IN', 'culture'),
    ('semporna_US', 'semporna', 'MY', 'US', 'beach'),
    ('humleb_k_US', 'humlebæk', 'DK', 'US', 'culture'),
    ('barreirinhas_US', 'barreirinhas', 'BR', 'US', 'culture'),
    ('barreirinhas_SG', 'barreirinhas', 'BR', 'SG', 'culture'),
    ('barreirinhas_AU', 'barreirinhas', 'BR', 'AU', 'culture'),
    ('barreirinhas_IN', 'barreirinhas', 'BR', 'IN', 'culture'),
    ('bergville_US', 'bergville', 'ZA', 'US', 'culture'),
    ('bergville_SG', 'bergville', 'ZA', 'SG', 'culture'),
    ('bergville_AU', 'bergville', 'ZA', 'AU', 'culture'),
    ('bergville_IN', 'bergville', 'ZA', 'IN', 'culture'),
    ('creel_US', 'creel', 'MX', 'US', 'culture'),
    ('creel_SG', 'creel', 'MX', 'SG', 'culture'),
    ('creel_AU', 'creel', 'MX', 'AU', 'culture'),
    ('creel_IN', 'creel', 'MX', 'IN', 'culture'),
    ('medellin_US', 'medellin', 'CO', 'US', 'culture'),
    ('musanze_US', 'musanze', 'RW', 'US', 'culture'),
    ('masvingo_US', 'masvingo', 'ZW', 'US', 'culture'),
    ('ouesso_US', 'ouesso', 'CG', 'US', 'culture'),
    ('dalanzadgad_US', 'dalanzadgad', 'MN', 'US', 'culture'),
    ('pangkalan_bun_US', 'pangkalan bun', 'ID', 'US', 'culture'),
    ('pangkalan_bun_SG', 'pangkalan bun', 'ID', 'SG', 'culture'),
    ('pangkalan_bun_AU', 'pangkalan bun', 'ID', 'AU', 'culture'),
    ('pangkalan_bun_IN', 'pangkalan bun', 'ID', 'IN', 'culture'),
    ('vestmanna_US', 'vestmanna', 'FO', 'US', 'culture'),
    ('razgrad_US', 'razgrad', 'BG', 'US', 'culture'),
    ('fl_m_US', 'flåm', 'NO', 'US', 'culture'),
    ('tef_US', 'tefé', 'BR', 'US', 'culture'),
    ('tef_SG', 'tefé', 'BR', 'SG', 'culture'),
    ('tef_AU', 'tefé', 'BR', 'AU', 'culture'),
    ('tef_IN', 'tefé', 'BR', 'IN', 'culture'),
    ('el_chalt_n_US', 'el chaltén', 'AR', 'US', 'culture'),
    ('taveuni_US', 'taveuni', 'FJ', 'US', 'beach'),
    ('ihosy_US', 'ihosy', 'MG', 'US', 'culture'),
    ('hexham_US', 'hexham', 'GB', 'US', 'culture'),
    ('hexham_SG', 'hexham', 'GB', 'SG', 'culture'),
    ('hexham_AU', 'hexham', 'GB', 'AU', 'culture'),
    ('hexham_IN', 'hexham', 'GB', 'IN', 'culture'),
    ('stockholm_US', 'stockholm', 'SE', 'US', 'culture'),
    ('valencia_US', 'valencia', 'ES', 'US', 'culture'),
    ('valencia_SG', 'valencia', 'ES', 'SG', 'culture'),
    ('valencia_AU', 'valencia', 'ES', 'AU', 'culture'),
    ('valencia_IN', 'valencia', 'ES', 'IN', 'culture'),
    ('tryphena_US', 'tryphena', 'NZ', 'US', 'culture'),
    ('tryphena_SG', 'tryphena', 'NZ', 'SG', 'culture'),
    ('tryphena_AU', 'tryphena', 'NZ', 'AU', 'culture'),
    ('tryphena_IN', 'tryphena', 'NZ', 'IN', 'culture'),
    ('ypres_US', 'ypres', 'BE', 'US', 'culture'),
    ('george_town_US', 'george town', 'BS', 'US', 'culture'),
    ('kilwa_masoko_US', 'kilwa masoko', 'TZ', 'US', 'culture'),
    ('jukkasj_rvi_US', 'jukkasjärvi', 'SE', 'US', 'culture'),
    ('luquillo_US', 'luquillo', 'PR', 'US', 'beach'),
    ('erdenet_US', 'erdenet', 'MN', 'US', 'culture'),
    ('chi_in_u_US', 'chișinău', 'MD', 'US', 'culture'),
    ('tours_US', 'tours', 'FR', 'US', 'culture'),
    ('tours_SG', 'tours', 'FR', 'SG', 'culture'),
    ('tours_AU', 'tours', 'FR', 'AU', 'culture'),
    ('tours_IN', 'tours', 'FR', 'IN', 'culture'),
    ('banaue_US', 'banaue', 'PH', 'US', 'culture'),
    ('giverny_US', 'giverny', 'FR', 'US', 'culture'),
    ('giverny_SG', 'giverny', 'FR', 'SG', 'culture'),
    ('giverny_AU', 'giverny', 'FR', 'AU', 'culture'),
    ('giverny_IN', 'giverny', 'FR', 'IN', 'culture'),
    ('roseau_US', 'roseau', 'DM', 'US', 'culture'),
    ('porthmadog_US', 'porthmadog', 'GB', 'US', 'culture'),
    ('porthmadog_SG', 'porthmadog', 'GB', 'SG', 'culture'),
    ('porthmadog_AU', 'porthmadog', 'GB', 'AU', 'culture'),
    ('porthmadog_IN', 'porthmadog', 'GB', 'IN', 'culture'),
    ('el_jem_US', 'el jem', 'TN', 'US', 'culture'),
    ('pinh_o_US', 'pinhão', 'PT', 'US', 'culture'),
    ('pinh_o_SG', 'pinhão', 'PT', 'SG', 'culture'),
    ('pinh_o_AU', 'pinhão', 'PT', 'AU', 'culture'),
    ('pinh_o_IN', 'pinhão', 'PT', 'IN', 'culture'),
    ('matmata_US', 'matmata', 'TN', 'US', 'culture'),
    ('dundee_US', 'dundee', 'GB', 'US', 'culture'),
    ('dundee_SG', 'dundee', 'GB', 'SG', 'culture'),
    ('dundee_AU', 'dundee', 'GB', 'AU', 'culture'),
    ('dundee_IN', 'dundee', 'GB', 'IN', 'culture'),
    ('sagres_US', 'sagres', 'PT', 'US', 'culture'),
    ('sagres_SG', 'sagres', 'PT', 'SG', 'culture'),
    ('sagres_AU', 'sagres', 'PT', 'AU', 'culture'),
    ('sagres_IN', 'sagres', 'PT', 'IN', 'culture'),
    ('hamburg_US', 'hamburg', 'DE', 'US', 'culture'),
    ('guilin_US', 'guilin', 'CN', 'US', 'culture'),
    ('hobart_US', 'hobart', 'AU', 'US', 'culture'),
    ('hobart_SG', 'hobart', 'AU', 'SG', 'culture'),
    ('hobart_AU', 'hobart', 'AU', 'AU', 'culture'),
    ('hobart_IN', 'hobart', 'AU', 'IN', 'culture'),
    ('lusaka_US', 'lusaka', 'ZM', 'US', 'culture'),
    ('sur_US', 'sur', 'OM', 'US', 'culture'),
    ('ulaanbaatar_US', 'ulaanbaatar', 'MN', 'US', 'culture'),
    ('akureyri_US', 'akureyri', 'IS', 'US', 'culture'),
    ('lijiang_US', 'lijiang', 'CN', 'US', 'culture'),
    ('carrick_US', 'carrick', 'IE', 'US', 'culture'),
    ('stirling_US', 'stirling', 'GB', 'US', 'culture'),
    ('stirling_SG', 'stirling', 'GB', 'SG', 'culture'),
    ('stirling_AU', 'stirling', 'GB', 'AU', 'culture'),
    ('stirling_IN', 'stirling', 'GB', 'IN', 'culture'),
    ('brussels_US', 'brussels', 'BE', 'US', 'culture'),
    ('esbjerg_US', 'esbjerg', 'DK', 'US', 'culture'),
    ('bar_harbor_US', 'bar harbor', 'US', 'US', 'culture'),
    ('bar_harbor_SG', 'bar harbor', 'US', 'SG', 'culture'),
    ('bar_harbor_AU', 'bar harbor', 'US', 'AU', 'culture'),
    ('bar_harbor_IN', 'bar harbor', 'US', 'IN', 'culture'),
    ('liverpool_US', 'liverpool', 'GB', 'US', 'culture'),
    ('liverpool_SG', 'liverpool', 'GB', 'SG', 'culture'),
    ('liverpool_AU', 'liverpool', 'GB', 'AU', 'culture'),
    ('liverpool_IN', 'liverpool', 'GB', 'IN', 'culture'),
    ('la_digue_US', 'la digue', 'SC', 'US', 'beach'),
    ('st_davids_US', 'st davids', 'GB', 'US', 'culture'),
    ('st_davids_SG', 'st davids', 'GB', 'SG', 'culture'),
    ('st_davids_AU', 'st davids', 'GB', 'AU', 'culture'),
    ('st_davids_IN', 'st davids', 'GB', 'IN', 'culture'),
    ('stavanger_US', 'stavanger', 'NO', 'US', 'culture'),
    ('belfast_US', 'belfast', 'GB', 'US', 'culture'),
    ('belfast_SG', 'belfast', 'GB', 'SG', 'culture'),
    ('belfast_AU', 'belfast', 'GB', 'AU', 'culture'),
    ('belfast_IN', 'belfast', 'GB', 'IN', 'culture'),
    ('sarajevo_US', 'sarajevo', 'BA', 'US', 'culture'),
    ('geneva_US', 'geneva', 'CH', 'US', 'culture'),
    ('baddeck_US', 'baddeck', 'CA', 'US', 'culture'),
    ('vis_US', 'vis', 'HR', 'US', 'beach'),
    ('vis_SG', 'vis', 'HR', 'SG', 'beach'),
    ('vis_AU', 'vis', 'HR', 'AU', 'beach'),
    ('vis_IN', 'vis', 'HR', 'IN', 'beach'),
    ('moshi_US', 'moshi', 'TZ', 'US', 'culture'),
    ('kandy_US', 'kandy', 'LK', 'US', 'culture'),
    ('naryn_US', 'naryn', 'KG', 'US', 'culture'),
    ('chicago_US', 'chicago', 'US', 'US', 'culture'),
    ('chicago_SG', 'chicago', 'US', 'SG', 'culture'),
    ('chicago_AU', 'chicago', 'US', 'AU', 'culture'),
    ('chicago_IN', 'chicago', 'US', 'IN', 'culture'),
    ('cape_coast_US', 'cape coast', 'GH', 'US', 'culture'),
    ('figueres_US', 'figueres', 'ES', 'US', 'culture'),
    ('figueres_SG', 'figueres', 'ES', 'SG', 'culture'),
    ('figueres_AU', 'figueres', 'ES', 'AU', 'culture'),
    ('figueres_IN', 'figueres', 'ES', 'IN', 'culture'),
    ('poprad_US', 'poprad', 'SK', 'US', 'culture'),
    ('m_laga_US', 'málaga', 'ES', 'US', 'culture'),
    ('m_laga_SG', 'málaga', 'ES', 'SG', 'culture'),
    ('m_laga_AU', 'málaga', 'ES', 'AU', 'culture'),
    ('m_laga_IN', 'málaga', 'ES', 'IN', 'culture'),
    ('quito_US', 'quito', 'EC', 'US', 'culture'),
    ('himeji_US', 'himeji', 'JP', 'US', 'culture'),
    ('himeji_SG', 'himeji', 'JP', 'SG', 'culture'),
    ('himeji_AU', 'himeji', 'JP', 'AU', 'culture'),
    ('himeji_IN', 'himeji', 'JP', 'IN', 'culture'),
    ('hampi_US', 'hampi', 'IN', 'US', 'culture'),
    ('hampi_SG', 'hampi', 'IN', 'SG', 'culture'),
    ('hampi_AU', 'hampi', 'IN', 'AU', 'culture'),
    ('hampi_IN', 'hampi', 'IN', 'IN', 'culture'),
    ('bonito_US', 'bonito', 'BR', 'US', 'culture'),
    ('bonito_SG', 'bonito', 'BR', 'SG', 'culture'),
    ('bonito_AU', 'bonito', 'BR', 'AU', 'culture'),
    ('bonito_IN', 'bonito', 'BR', 'IN', 'culture'),
    ('halfmoon_bay_US', 'halfmoon bay', 'NZ', 'US', 'culture'),
    ('halfmoon_bay_SG', 'halfmoon bay', 'NZ', 'SG', 'culture'),
    ('halfmoon_bay_AU', 'halfmoon bay', 'NZ', 'AU', 'culture'),
    ('halfmoon_bay_IN', 'halfmoon bay', 'NZ', 'IN', 'culture'),
    ('labuan_bajo_US', 'labuan bajo', 'ID', 'US', 'culture'),
    ('labuan_bajo_SG', 'labuan bajo', 'ID', 'SG', 'culture'),
    ('labuan_bajo_AU', 'labuan bajo', 'ID', 'AU', 'culture'),
    ('labuan_bajo_IN', 'labuan bajo', 'ID', 'IN', 'culture'),
    ('bergen_US', 'bergen', 'NO', 'US', 'culture'),
    ('dublin_US', 'dublin', 'IE', 'US', 'culture'),
    ('ouarzazate_US', 'ouarzazate', 'MA', 'US', 'culture'),
    ('ouarzazate_SG', 'ouarzazate', 'MA', 'SG', 'culture'),
    ('ouarzazate_AU', 'ouarzazate', 'MA', 'AU', 'culture'),
    ('ouarzazate_IN', 'ouarzazate', 'MA', 'IN', 'culture'),
    ('san_ignacio_US', 'san ignacio', 'BZ', 'US', 'culture'),
    ('carcassonne_US', 'carcassonne', 'FR', 'US', 'culture'),
    ('carcassonne_SG', 'carcassonne', 'FR', 'SG', 'culture'),
    ('carcassonne_AU', 'carcassonne', 'FR', 'AU', 'culture'),
    ('carcassonne_IN', 'carcassonne', 'FR', 'IN', 'culture'),
    ('neiva_US', 'neiva', 'CO', 'US', 'culture'),
    ('monteverde_US', 'monteverde', 'CR', 'US', 'culture'),
    ('provincetown_US', 'provincetown', 'US', 'US', 'culture'),
    ('provincetown_SG', 'provincetown', 'US', 'SG', 'culture'),
    ('provincetown_AU', 'provincetown', 'US', 'AU', 'culture'),
    ('provincetown_IN', 'provincetown', 'US', 'IN', 'culture'),
    ('mal_US', 'malé', 'MV', 'US', 'beach'),
    ('potsdam_US', 'potsdam', 'DE', 'US', 'culture'),
    ('zhangjiajie_US', 'zhangjiajie', 'CN', 'US', 'culture'),
    ('preah_vihear_city_US', 'preah vihear city', 'KH', 'US', 'culture'),
    ('san_pedro_US', 'san pedro', 'BZ', 'US', 'culture'),
    ('cochrane_US', 'cochrane', 'CL', 'US', 'culture'),
    ('henties_bay_US', 'henties bay', 'NA', 'US', 'culture'),
    ('nagasaki_US', 'nagasaki', 'JP', 'US', 'culture'),
    ('nagasaki_SG', 'nagasaki', 'JP', 'SG', 'culture'),
    ('nagasaki_AU', 'nagasaki', 'JP', 'AU', 'culture'),
    ('nagasaki_IN', 'nagasaki', 'JP', 'IN', 'culture'),
    ('bucharest_US', 'bucharest', 'RO', 'US', 'culture'),
    ('mecca_US', 'mecca', 'SA', 'US', 'culture'),
    ('york_US', 'york', 'GB', 'US', 'culture'),
    ('york_SG', 'york', 'GB', 'SG', 'culture'),
    ('york_AU', 'york', 'GB', 'AU', 'culture'),
    ('york_IN', 'york', 'GB', 'IN', 'culture'),
    ('santa_catalina_US', 'santa catalina', 'PA', 'US', 'beach'),
    ('la_paz_US', 'la paz', 'MX', 'US', 'beach'),
    ('la_paz_SG', 'la paz', 'MX', 'SG', 'beach'),
    ('la_paz_AU', 'la paz', 'MX', 'AU', 'beach'),
    ('la_paz_IN', 'la paz', 'MX', 'IN', 'beach'),
    ('egilssta_ir_US', 'egilsstaðir', 'IS', 'US', 'culture'),
    ('santa_marta_US', 'santa marta', 'CO', 'US', 'culture'),
    ('mendoza_US', 'mendoza', 'AR', 'US', 'culture'),
    ('rotterdam_US', 'rotterdam', 'NL', 'US', 'culture'),
    ('mellie_a_US', 'mellieħa', 'MT', 'US', 'culture'),
    ('belgrade_US', 'belgrade', 'RS', 'US', 'culture'),
    ('luxembourg_city_US', 'luxembourg city', 'LU', 'US', 'culture'),
    ('nizwa_US', 'nizwa', 'OM', 'US', 'culture'),
    ('huangshan_US', 'huangshan', 'CN', 'US', 'culture'),
    ('khiva_US', 'khiva', 'UZ', 'US', 'culture'),
    ('pakse_US', 'pakse', 'LA', 'US', 'culture'),
    ('glasgow_US', 'glasgow', 'GB', 'US', 'culture'),
    ('glasgow_SG', 'glasgow', 'GB', 'SG', 'culture'),
    ('glasgow_AU', 'glasgow', 'GB', 'AU', 'culture'),
    ('glasgow_IN', 'glasgow', 'GB', 'IN', 'culture'),
    ('porto_US', 'porto', 'PT', 'US', 'culture'),
    ('porto_SG', 'porto', 'PT', 'SG', 'culture'),
    ('porto_AU', 'porto', 'PT', 'AU', 'culture'),
    ('porto_IN', 'porto', 'PT', 'IN', 'culture'),
    ('san_juan_US', 'san juan', 'PR', 'US', 'culture'),
    ('baku_US', 'baku', 'AZ', 'US', 'culture'),
    ('tbilisi_US', 'tbilisi', 'GE', 'US', 'culture'),
    ('kigali_US', 'kigali', 'RW', 'US', 'culture'),
    ('paphos_US', 'paphos', 'CY', 'US', 'culture'),
    ('con_son_US', 'con son', 'VN', 'US', 'culture'),
    ('anakkale_US', 'çanakkale', 'TR', 'US', 'culture'),
    ('gdansk_US', 'gdansk', 'PL', 'US', 'culture'),
    ('brno_US', 'brno', 'CZ', 'US', 'culture'),
    ('leshan_US', 'leshan', 'CN', 'US', 'culture'),
    ('innsbruck_US', 'innsbruck', 'AT', 'US', 'culture'),
    ('bordeaux_US', 'bordeaux', 'FR', 'US', 'culture'),
    ('bordeaux_SG', 'bordeaux', 'FR', 'SG', 'culture'),
    ('bordeaux_AU', 'bordeaux', 'FR', 'AU', 'culture'),
    ('bordeaux_IN', 'bordeaux', 'FR', 'IN', 'culture'),
    ('penrhyndeudraeth_US', 'penrhyndeudraeth', 'GB', 'US', 'culture'),
    ('penrhyndeudraeth_SG', 'penrhyndeudraeth', 'GB', 'SG', 'culture'),
    ('penrhyndeudraeth_AU', 'penrhyndeudraeth', 'GB', 'AU', 'culture'),
    ('penrhyndeudraeth_IN', 'penrhyndeudraeth', 'GB', 'IN', 'culture'),
    ('bogot_US', 'bogotá', 'CO', 'US', 'culture'),
    ('aomori_US', 'aomori', 'JP', 'US', 'culture'),
    ('aomori_SG', 'aomori', 'JP', 'SG', 'culture'),
    ('aomori_AU', 'aomori', 'JP', 'AU', 'culture'),
    ('aomori_IN', 'aomori', 'JP', 'IN', 'culture'),
    ('dessau_US', 'dessau', 'DE', 'US', 'culture'),
    ('homestead_US', 'homestead', 'US', 'US', 'culture'),
    ('homestead_SG', 'homestead', 'US', 'SG', 'culture'),
    ('homestead_AU', 'homestead', 'US', 'AU', 'culture'),
    ('homestead_IN', 'homestead', 'US', 'IN', 'culture'),
    ('rila_US', 'rila', 'BG', 'US', 'culture'),
    ('churchill_US', 'churchill', 'CA', 'US', 'culture'),
    ('segovia_US', 'segovia', 'ES', 'US', 'culture'),
    ('segovia_SG', 'segovia', 'ES', 'SG', 'culture'),
    ('segovia_AU', 'segovia', 'ES', 'AU', 'culture'),
    ('segovia_IN', 'segovia', 'ES', 'IN', 'culture'),
    ('krems_US', 'krems', 'AT', 'US', 'culture'),
    ('fort_macleod_US', 'fort macleod', 'CA', 'US', 'culture'),
    ('krak_w_US', 'kraków', 'PL', 'US', 'culture'),
    ('budva_US', 'budva', 'ME', 'US', 'culture'),
    ('djibouti_city_US', 'djibouti city', 'DJ', 'US', 'culture'),
    ('oranjestad_US', 'oranjestad', 'AW', 'US', 'beach'),
    ('dijon_US', 'dijon', 'FR', 'US', 'culture'),
    ('dijon_SG', 'dijon', 'FR', 'SG', 'culture'),
    ('dijon_AU', 'dijon', 'FR', 'AU', 'culture'),
    ('dijon_IN', 'dijon', 'FR', 'IN', 'culture'),
    ('selfoss_US', 'selfoss', 'IS', 'US', 'culture'),
    # --- #54 country-representative coverage: 64 catalog countries previously
    # untested through negotiate() (capital/largest city each; warzones excluded).
    # All verified success+booking via the demo merchant (8090) on 2026-06-23.
    ('andorra_la_vella_AD_cov', 'andorra la vella', 'AD', 'US', 'culture'),
    ('saint_john_s_AG_cov', 'saint john’s', 'AG', 'US', 'culture'),
    ('arabkir_AM_cov', 'arabkir', 'AM', 'US', 'culture'),
    ('benfica_AO_cov', 'benfica', 'AO', 'US', 'culture'),
    ('bridgetown_BB_cov', 'bridgetown', 'BB', 'US', 'culture'),
    ('bhatara_BD_cov', 'bhatara', 'BD', 'US', 'culture'),
    ('al_muharraq_BH_cov', 'al muharraq', 'BH', 'US', 'culture'),
    ('bujumbura_BI_cov', 'bujumbura', 'BI', 'US', 'culture'),
    ('abomey_BJ_cov', 'abomey', 'BJ', 'US', 'culture'),
    ('bandar_seri_begawan_BN_cov', 'bandar seri begawan', 'BN', 'US', 'culture'),
    ('minsk_BY_cov', 'minsk', 'BY', 'US', 'culture'),
    ('san_pedro_CI_cov', 'san pedro', 'CI', 'US', 'culture'),
    ('bafoussam_CM_cov', 'bafoussam', 'CM', 'US', 'culture'),
    ('praia_CV_cov', 'praia', 'CV', 'US', 'culture'),
    ('bella_vista_DO_cov', 'bella vista', 'DO', 'US', 'culture'),
    ('palikir_FM_cov', 'palikir', 'FM', 'US', 'culture'),
    ('libreville_GA_cov', 'libreville', 'GA', 'US', 'culture'),
    ('saint_george_s_GD_cov', "saint george's", 'GD', 'US', 'culture'),
    ('serekunda_GM_cov', 'serekunda', 'GM', 'US', 'culture'),
    ('camayenne_GN_cov', 'camayenne', 'GN', 'US', 'culture'),
    ('bata_GQ_cov', 'bata', 'GQ', 'US', 'culture'),
    ('bissau_GW_cov', 'bissau', 'GW', 'US', 'culture'),
    ('georgetown_GY_cov', 'georgetown', 'GY', 'US', 'culture'),
    ('victoria_HK_cov', 'victoria', 'HK', 'US', 'culture'),
    ('el_progreso_HN_cov', 'el progreso', 'HN', 'US', 'culture'),
    ('haifa_IL_cov', 'haifa', 'IL', 'US', 'culture'),
    ('new_kingston_JM_cov', 'new kingston', 'JM', 'US', 'culture'),
    ('tarawa_KI_cov', 'tarawa', 'KI', 'US', 'culture'),
    ('moroni_KM_cov', 'moroni', 'KM', 'US', 'culture'),
    ('basseterre_KN_cov', 'basseterre', 'KN', 'US', 'culture'),
    ('al_ahmadi_KW_cov', 'al ahmadi', 'KW', 'US', 'culture'),
    ('gros_islet_LC_cov', 'gros islet', 'LC', 'US', 'culture'),
    ('vaduz_LI_cov', 'vaduz', 'LI', 'US', 'culture'),
    ('monrovia_LR_cov', 'monrovia', 'LR', 'US', 'culture'),
    ('maseru_LS_cov', 'maseru', 'LS', 'US', 'culture'),
    ('kaunas_LT_cov', 'kaunas', 'LT', 'US', 'culture'),
    ('riga_LV_cov', 'riga', 'LV', 'US', 'culture'),
    ('monte_carlo_MC_cov', 'monte-carlo', 'MC', 'US', 'culture'),
    ('dalap_uliga_dorrit_MH_cov', 'dalap-uliga-dorrit', 'MH', 'US', 'culture'),
    ('skopje_MK_cov', 'skopje', 'MK', 'US', 'culture'),
    ('macau_MO_cov', 'macau', 'MO', 'US', 'culture'),
    ('nouadhibou_MR_cov', 'nouadhibou', 'MR', 'US', 'culture'),
    ('beau_bassin_rose_hill_MU_cov', 'beau bassin-rose hill', 'MU', 'US', 'culture'),
    ('abuja_NG_cov', 'abuja', 'NG', 'US', 'culture'),
    ('yaren_NR_cov', 'yaren', 'NR', 'US', 'culture'),
    ('asuncion_PY_cov', 'asuncion', 'PY', 'US', 'culture'),
    ('doha_QA_cov', 'doha', 'QA', 'US', 'culture'),
    ('honiara_SB_cov', 'honiara', 'SB', 'US', 'culture'),
    ('bo_SL_cov', 'bo', 'SL', 'US', 'culture'),
    ('san_marino_SM_cov', 'san marino', 'SM', 'US', 'culture'),
    ('paramaribo_SR_cov', 'paramaribo', 'SR', 'US', 'culture'),
    ('sao_tome_ST_cov', 'sao tome', 'ST', 'US', 'culture'),
    ('mejicanos_SV_cov', 'mejicanos', 'SV', 'US', 'culture'),
    ('n_djamena_TD_cov', "n'djamena", 'TD', 'US', 'culture'),
    ('kara_TG_cov', 'kara', 'TG', 'US', 'culture'),
    ('dili_TL_cov', 'dili', 'TL', 'US', 'culture'),
    ('ashgabat_TM_cov', 'ashgabat', 'TM', 'US', 'culture'),
    ('nuku_alofa_TO_cov', 'nuku‘alofa', 'TO', 'US', 'culture'),
    ('scarborough_TT_cov', 'scarborough', 'TT', 'US', 'culture'),
    ('funafuti_TV_cov', 'funafuti', 'TV', 'US', 'culture'),
    ('montevideo_UY_cov', 'montevideo', 'UY', 'US', 'culture'),
    ('calliaqua_VC_cov', 'calliaqua', 'VC', 'US', 'culture'),
    ('barinas_VE_cov', 'barinas', 'VE', 'US', 'culture'),
    ('port_vila_VU_cov', 'port-vila', 'VU', 'US', 'culture'),
]


class TestE2ECountryCoverage(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.orch = build_society()

    def test_all_countries(self):
        anomalies = []
        total = 0
        for label, city, iso, nat, vibe in CASES:
            if iso in WARZONE_ISO:
                continue
            total += 1
            trip = _trip(city, iso, nationality=nat, vibe=vibe)
            try:
                r1 = self.orch.negotiate(trip)
                r2 = self.orch.negotiate(trip)  # var-0 check
            except Exception as e:
                anomalies.append(f"CRASH {label}: {type(e).__name__}: {e}")
                continue

            # Must return a known outcome — never None or unknown
            if r1.get("outcome") not in _KNOWN_OUTCOMES:
                anomalies.append(
                    f"UNKNOWN_OUTCOME {label}: {r1.get('outcome')!r}"
                )

            # Var-0: outcome and visa fee must be stable across two identical runs
            stable1 = json.dumps({
                "outcome": r1.get("outcome"),
                "visa_fee": (r1.get("compliance") or {}).get("total_visa_fee_usd_cents"),
            }, sort_keys=True)
            stable2 = json.dumps({
                "outcome": r2.get("outcome"),
                "visa_fee": (r2.get("compliance") or {}).get("total_visa_fee_usd_cents"),
            }, sort_keys=True)
            if stable1 != stable2:
                anomalies.append(
                    f"VARIANCE {label}: {stable1} != {stable2}"
                )

        print(f"\nE2E: {total} cases run, {len(anomalies)} anomalies")
        for a in anomalies[:30]:
            print(" -", a)
        self.assertEqual(
            anomalies, [],
            f"{len(anomalies)} E2E anomalies (first shown above)",
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
